### ISSUE TITLE
ActionMode enabled/disabled

### ISSUE THREAD

**Issue by Knuth75** [De-Morgan/flutter-contextual-action-bar#1]
How can I know that the contextual appbar is in actionmode and how to disable programatically?

**Comment by De-Morgan** [comment]
This contextual action bar workaround does not support zero item in the ActionMode.

Use the ActionMode.addItem<?> to add an item to the selected items. If this is the first selection, the ActionMode is will be enabled.

Use the ActionMode.addItems<?> to add a list of items.

Use the ActionMode.disableActionMode<?> to disable and deselect all selected items.

Note: In most cases, you won't need to use ActionMode.disableActionMode<?> because the package already do that for you where needed.

**Comment by De-Morgan** [comment]
The contextual action bar does not support zero item in the ActionMode.

Use the ActionMode.addItem<?> to add an item to the selected items. If this is the first selection, the ActionMode is will be enabled.

Use the ActionMode.addItems<?> to add a list of items.

Use the ActionMode.disableActionMode<?> to disable and deselect all selected items.

Note: In most cases, you won't need to use ActionMode.disableActionMode<?> because the package already do that for you where needed.
